### ISSUE TITLE
dealing with duplicate place names

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN#211] opened 2018-11-14 20:40 UTC
follow up of #181 @jsblgpn

> how to deal with cases like Apameia in Syria and Apameia-Pella in Syria: this is the same place

New listings of places (alphabetical and nested) should help identifying duplicates. Once duplicates are identified following tasks need to be executed:

1. all nested places from superfluous entry need to be chained to the correct one
2. all person records linked to the superfluous entry need to be adjusted to the correct one

Both tasks can be automated, so I could prepare a dropdown box next to place entry in the list where correct place could be selected and all the person and place records would be updated accordingly and superfluous place removed. Does this sound ok?

<img width="711" alt="image" src="https://user-images.githubusercontent.com/449468/48511012-c9c81f80-e855-11e8-9d33-7f0079df773d.png">

**Comment by JSBLGPN** [comment] 2018-11-15 09:00
Yes, it might be a good idea. There is also the question of places that won't appear in the book. Perhaps it would be good to think about all the issues related to place names together.

**Comment by JSBLGPN** [comment] 2018-11-15 09:08
There are places like Commagene and Kommagene, which have nested places and I wonder if this is going to create problems...

**Comment by tuurma** [comment] 2019-02-15 11:46
For simplicity I've changed the interface design. Now it has two dropdowns: first one is to choose the place which is redundant and the other the target place. As a result, after merge is confirmed, all people linked to the redundant place and all places nested within it will be updated to point to the target place. 

Metadata indexes for all affected records are updated as well so search results should be correct. Please note that the list of places below the form does not refresh automatically so to see

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/449468/52852391-bd838500-3118-11e9-893c-c387f9283f89.png">

confirmation dialog

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/449468/52854540-fde60180-311e-11e9-8f80-bccba90e96d1.png">

finishing dialog

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/449468/52854588-28d05580-311f-11e9-8cdb-6d3df9649384.png">

state after page refresh (note that person count in the target place has been increased)

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/449468/52854639-561d0380-311f-11e9-9c6c-94c6856ddf8f.png">

**Comment by tuurma** [comment] 2019-02-15 11:47
NB merge example above is of course nonsensical and only done for illustration on my local copy :-)

I will update the server tonight.

**Comment by tuurma** [comment] 2019-02-15 12:29
* [x] updating list of nested places after merge is still missing

**Comment by tuurma** [comment] 2019-02-15 12:31
merging two Aiolis places:

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/449468/52856849-ce86c300-3125-11e9-9eb6-d4b3f51e47bb.png">

expected result after refresh:

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/449468/52856924-f2e29f80-3125-11e9-8ff1-073dc8434a4a.png">

**Comment by tuurma** [comment] 2019-02-15 12:45
testing locally on Kommagene -> Commagene

before:

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/449468/52857461-836daf80-3127-11e9-9dfd-ddfa3f1c1294.png">

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/449468/52857543-c3cd2d80-3127-11e9-9db9-8e801ea2a819.png">

merging: 

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/449468/52857477-8f597180-3127-11e9-83b3-07ebd0256f0a.png">

after:

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/449468/52857586-e9f2cd80-3127-11e9-84bf-d2618c92c647.png">

**Comment by tuurma** [comment] 2019-02-15 12:50
seems all to work fine now locally, server update scheduled tonight

**Comment by JSBLGPN** [comment] 2019-02-21 14:29
My first attempt to merge two places (Apameia, Syria, LGPN 70060 with Pella-Apameia, Syria) failed...after merging was going on for 5-10 minutes I just stopped the process. Is it supposed to take so long? I am not sure whether some entires were changed.

**Comment by tuurma** [comment] 2019-02-22 11:49
This is current state with Apameia and Pella-Apameia, does it look like the merge has been successful? There are no persons registered in Apameia anymore, just 430 in Pella-Apameia.

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/449468/53240629-832d6100-369f-11e9-92e8-9d1028980776.png">

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/449468/53240659-98a28b00-369f-11e9-81cf-149760fda43e.png">

To test further, I've tried merging these two places again and got expected results in just couple seconds.

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/449468/53240851-1cf50e00-36a0-11e9-8d9b-5c57acd972f8.png">

**Comment by tuurma** [comment] 2019-02-22 11:53
As a test, when you identify further merge candidates, could you first take a screenshot of how many persons and subplaces are registered in each (via Place catalogue and/or List of nested places). Then after performing the merge (which should not take long, just few seconds) refresh the place catalogue and check the numbers - the target place should have a sum of person entries and nested places and the other place should be deleted.

**Comment by JSBLGPN** [comment] 2019-02-22 14:48
Apameia no longer appears in my place catalogue. But the number of people under Pella-Apameia seems to include Pella-Apameia + Apameia (Syria), so that's all right.
I will do more merging later.

**Comment by JSBLGPN** [comment] 2019-02-25 12:02
I need to merge the two Laodikeia in Syria
![laodikeia2](https://user-images.githubusercontent.com/18262359/53335711-1d85e280-38f4-11e9-9b9b-ded0c573b026.PNG)

![laodikeia](https://user-images.githubusercontent.com/18262359/53335719-237bc380-38f4-11e9-83d6-5847fdf52ba0.PNG)

Before merging I need to check the 52 individuals placed under Laodikeia (LGPN 50480) and see whether they all go under Laodikeia (LGPN P6ae93e8e-ee03-4317-8d45-cbd1e890329c) or some go under Laodikeia near Libanon or even another Laodikeia. 

The problem is that when we search for people from Laodikeia all people put under one Laodikeia are retrieved...so 373 people.... What I want is to retrieve the 52 from LGPN 50480 and check them...It is not possible to search by ID place number. How can we solve that?

![laodikeia3](https://user-images.githubusercontent.com/18262359/53335906-aac93700-38f4-11e9-9b66-bc66060ef089.PNG)

Thanks

**Comment by tuurma** [comment] 2019-02-27 11:41
I have actually added filtering by place-id, not just by place name the other time - needed it when preparing the links from lists of places, so it's enough to choose place-id and give the exact id of a place.

LGPN_50480

<img width="1656" alt="image" src="https://user-images.githubusercontent.com/449468/53487550-27dae480-3a8c-11e9-88e4-58ac95fb1f5f.png">

P6ae93e8e-ee03-4317-8d45-cbd1e890329c

<img width="1662" alt="image" src="https://user-images.githubusercontent.com/449468/53487468-f3672880-3a8b-11e9-9b37-daeff00726c1.png">

**Comment by JSBLGPN** [comment] 2019-02-27 15:43
I merged the two Laodikeia (Syria): numbers do not match...

Before merging (picture 1):
![laodikeia](https://user-images.githubusercontent.com/18262359/53502049-2ff34e00-3aa5-11e9-9c49-1523061fb944.PNG)

After merging (picture 2):
![aftermerginlaod](https://user-images.githubusercontent.com/18262359/53502065-38e41f80-3aa5-11e9-9687-bc1070c16d0c.PNG)

So we would expect to have 341 people under Laodikeia and we've got 348 + 4 dependent communities.
Picture 1 is from proofing vol 6 places alphabetically and picture 2 is from place catalogue...souldn't they match?

Picture 3 is from nested places:
![nested places](https://user-images.githubusercontent.com/18262359/53502582-51086e80-3aa6-11e9-92f0-ea745025f404.PNG)

**Comment by tuurma** [comment] 2019-02-27 17:55
Filtering for just the place name returns 348 entries

<img width="1647" alt="image" src="https://user-images.githubusercontent.com/449468/53511520-eca6d880-3ac0-11e9-884b-7066a4bd2aa8.png">

but for the place AND V6 only 341, which is what nested and alphabetical lists show (only V6)

<img width="1653" alt="image" src="https://user-images.githubusercontent.com/449468/53511781-75be0f80-3ac1-11e9-8508-a4d50fba68c8.png">


Hope this explains the difference in numbers. All lists under Proofing tab are limited to V6

**Comment by JSBLGPN** [comment] 2019-02-27 17:59
Thanks, yes, I understand: probably 7 people attested in Laodikeia, but belonging to other volumes, so not appearing in V6 lists.

**Comment by tuurma** [comment] 2019-02-27 18:08
Exactly the mechanism you described. But checking this, I noticed majority of these 'missing' records in Laodikeia has no volume assigned.

Here are the person ids:

1
<person>P4bbda222-5cce-464b-8462-d92837b9b862 Other Ὁνορᾶτος</person>
2
<person>P08492131-5945-4cc4-adcf-b3e542462c2e  Ἀσκληπιάδης</person>
3
<person>P5d71ddee-80cb-475b-a158-403d3aa03715  Ὧρος</person>
4
<person>Pcc7dfde0-f81d-44dd-a129-1692e1b1a028  Ἀπολλόδωρος</person>
5
<person>P5371eaa7-de9c-4222-9895-6dd72854db37  Ἀπολλόδωρος</person>
6
<person>Pe5d57b48-de44-47ac-9876-094ef6461af5  Ἀντίοχος</person>
7
<person>Pa69c07fa-abcf-4c40-a514-49130f0d40ae Egypt Ἀπολλινάριος</person>

**Comment by tuurma** [comment] 2019-02-27 18:11
All in all there are 26 person records not assigned to any volume.

**Comment by JSBLGPN** [comment] 2019-02-27 18:13
If I can have a list of these 19 other records I will check that tomorrow.
Thanks a lot

**Comment by tuurma** [comment] 2019-02-27 18:29
<a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P3f52c025-63fa-4526-a252-3f724256a8f9">Οὐράνις</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P96a7581a-86a7-45fc-ab05-7cfd5b3c6f18">Ἀνίας</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pbe847be2-fdfc-4418-a225-c76e009c8766">Ομαθ</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P86bf8dde-61d3-4127-a03a-26954f73e0d3">Ἀντωνῖνος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P8c260577-e52d-483b-b4ae-cb18d6f6f2a8">Γέμελλος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pdaf6aa5c-9915-46db-9268-cc4b6892030c">Οὐάλης</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P51ecfa84-9703-412a-9380-0ea7d90b7331">Εὐσέβις</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P170ec316-04f6-4b2f-ac4a-916028bf443b">Ἄννιος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P74ccf593-9edd-4085-afe9-39898b8427f7">Δαμᾶς</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pcbe9d8dc-ef92-4f2f-9dec-585a888eb4c6">Εὔδωρος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pf5167768-043e-4d7e-a246-85850bd83be0">Μάρκελλος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P49cc8b32-d7b1-4713-94ac-9f16da85118c">Μαγαδελ</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pdba28919-69b1-46f2-ba66-64c0905afabb">Πρίσκος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P08492131-5945-4cc4-adcf-b3e542462c2e">Ἀσκληπιάδης</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P5d71ddee-80cb-475b-a158-403d3aa03715">Ὧρος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pcc7dfde0-f81d-44dd-a129-1692e1b1a028">Ἀπολλόδωρος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P5371eaa7-de9c-4222-9895-6dd72854db37">Ἀπολλόδωρος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pe5d57b48-de44-47ac-9876-094ef6461af5">Ἀντίοχος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pd15d673c-aa08-42ed-bf9b-6426871f783b">Τρυφέρα</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P8ece7413-64cb-43e9-9d95-3cad53103713">Φίλων</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P616f8145-f3c3-4d3f-a068-af4c928a55aa">Γορας</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P69fef714-82d2-46f1-8226-4657e65339ef">Ολπιανος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P46aa6bb7-75ac-4d98-bea9-63a5a46cf6a5">Γεώργιος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P94ccb691-cef5-4264-9d88-a9038aca8cd6">Ζηνόβις</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pe254c0ee-5af7-4e8a-99f5-8b573deeafdc">Ναγδας</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pcebbae3e-1f5b-4030-99ea-114b103f09b9">Λισεμσεος</a>

**Comment by JSBLGPN** [comment] 2019-02-28 15:43
Thanks. All checked and changed.

**Closed as completed** 2019-03-01 08:29 UTC
