### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#201] opened 2018-08-28 09:16 UTC
We notice that the search function returns incomplete results for secondary source references, e.g. if we search for "PIR" only two results are returned and there should be many more. Perhaps it would help to create a separate search filter "secondary source" alongside "reference"? We also note that the problem with paging in search results persists: i.e. page 2 repeats the first 10 or so results from page 1, and so on.

**Comment by tuurma** [comment] 2018-12-03 20:37
added the treatment for references to assume always ending in a wildcard, thus searches for PIR will also find PIR2 entries, please let me know if results look correct to you now?

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/449468/49400144-a94c0080-f743-11e8-87d5-aaa72579a03d.png">

**Comment by tuurma** [comment] 2018-12-03 22:09
Could you please let me know if the problem with paging still persists? Couldn't reproduce it.

**Comment by tuurma** [comment] 2018-12-03 22:25
Thought about adding trailing wildcard by default to reference searches but reconsidered as this would currently limit options for using phrase queries there. Thus to retrieve all PIR entries one would need to query for `PIR*` or  enclose the query in quotes to match complete phrase as shown below

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/449468/49405317-5ded1e80-f752-11e8-9c86-ae7b628b3464.png">

**Comment by tuurma** [comment] 2019-07-31 19:27
Meanwhile both paging and search issue mentioned above were fixed so closing

**Closed as completed by tuurma** 2019-07-31 19:27 UTC
